project_id = "emerald-spring-465406-s1"
region = "us-central1"
vpc_new1 = "custom-vpc"
subnet_name = "custom-subnet"
ip_cidr = "10.2.0.0/14"
vm_name = "vm-1"
zone = "us-central1-a"
machine_type = "e2-medium"